/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionPo implements Serializable {

    private static final long serialVersionUID = -1253958039;

    private final Long id;
    private final Byte uuid;

    public SessionPo(SessionPo value) {
        this.id = value.id;
        this.uuid = value.uuid;
    }

    public SessionPo(
        Long id,
        Byte uuid
    ) {
        this.id = id;
        this.uuid = uuid;
    }

    public Long getId() {
        return this.id;
    }

    public Byte getUuid() {
        return this.uuid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SessionPo (");

        sb.append(id);
        sb.append(", ").append(uuid);

        sb.append(")");
        return sb.toString();
    }
}
