/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.MessageTable;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>sharding_jdbc_test</code> 
 * schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MESSAGE_IDX_SESSION_ID = Indexes0.MESSAGE_IDX_SESSION_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index MESSAGE_IDX_SESSION_ID = Internal.createIndex("idx_session_id", MessageTable.MESSAGE, new OrderField[] { MessageTable.MESSAGE.SESSION_ID }, false);
    }
}
