/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.MessageTable;
import db.tables.SessionTable;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShardingJdbcTestSchema extends SchemaImpl {

    private static final long serialVersionUID = 1067704411;

    /**
     * The reference instance of <code>sharding_jdbc_test</code>
     */
    public static final ShardingJdbcTestSchema SHARDING_JDBC_TEST = new ShardingJdbcTestSchema();

    /**
     * The table <code>sharding_jdbc_test.message</code>.
     */
    public final MessageTable MESSAGE = MessageTable.MESSAGE;

    /**
     * The table <code>sharding_jdbc_test.session</code>.
     */
    public final SessionTable SESSION = SessionTable.SESSION;

    /**
     * No further instances allowed
     */
    private ShardingJdbcTestSchema() {
        super("sharding_jdbc_test", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            MessageTable.MESSAGE,
            SessionTable.SESSION);
    }
}
