/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.MessageTable;
import db.tables.SessionTable;


/**
 * Convenience access to all tables in sharding_jdbc_test
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sharding_jdbc_test.message</code>.
     */
    public static final MessageTable MESSAGE = MessageTable.MESSAGE;

    /**
     * The table <code>sharding_jdbc_test.session</code>.
     */
    public static final SessionTable SESSION = SessionTable.SESSION;
}
